version: 2
jobs:
  build-and-test:
    macos:
      xcode: "9.4.1"
    shell: /bin/bash --login -o pipefail
    steps:
      - checkout
      - run: xcodebuild -project FinniversKit.xcodeproj -scheme "Demo" -destination 'platform=iOS Simulator,OS=11.4,name=iPhone X' build test | xcpretty
workflows:
  version: 2
  build-and-test:
    jobs:
      - build-and-test
